### ISSUE TITLE
Scanning artifacts 

### ISSUE THREAD

**Issue by raacampbell** [VicidominiLab/BrightEyes-MCS#1]
* [x] The movie in the readme shows a flyback artifact in the fast axis. It would be nice if this was corrected. 
* [x] #3

**Comment by mattia-donato** [comment]
Thank you. We preferred to store and show all data acquired during a scan. If necessary, users can easily crop the data during the analysis phase. The software and firmware support bidirectional scanning, which can be enabled through the "snake walk" checkbox in the GUI. While this feature functions as intended, unidirectional scanning is generally preferred for real measurements, as it results in a more uniform image. In bidirectional scanning, the odd and even lines often do not align properly. This misalignment is caused by a similar mechanism to the flyback effect, where there the actual position do not correspond to the position assumed by the acquisition system. Here, there is a time delay between the command signal (sent as voltage to the mirror) and the actual position of the mirror. This delay is influenced by physical factors of the galvo (mass inertia, PID control, and the power of the galvos, etc...) and the speed requested. This means that by keeping the same pixel dwell-time, zooming out _(in)_ a shows in the unidirectional mode a larger _(smaller)_ flyback artifact, and in the bidirectional mode a larger _(smaller)_ misalligment effect along x axis between the odd and even lines.

**Comment by raacampbell** [comment]
Obviously this is a design choice without a right or wrong answer. That said, it has been my experience that users are confused by the flyback artifact and they find it unexpected that part of the image needs be cropped. i.e. they don't like ending up with non-square images and don't see why it has to be so. The flyback artifact and bidirectional scanning phase correction are both solved nicely in [ScanImage](https://www.mbfbioscience.com/products/scanimage/) (see [free version on GitHub](https://github.com/PTRRupprecht/Instrument-Control/tree/master/ScanImage%20B/ScanImagePR) and [as a minimal example](https://github.com/SWC-Advanced-Microscopy/SimpleMScanner)) and are nice to have. It's not too much work to make the image uniformity of bidi indistinguishable from unidirectional so long as the scanning parameters are within the limits of the PID loop.
